void program (void);
void declrscope (void);
void varlist (void);
void tmodifier (void);
void stmtscope (void);
void stmtlist (void);
void stmt (void);
void ifstmt (void);
void whilestmt (void);
void forstmt (void);
void repstmt (void);
void wrtstmt (void);
void exprlist (void);
void rdstmt (void);
void assgnm (void);
void var (void);
void expr (void);
void relop (void);
void laexp (void);
int unary (void);
void addop (void);
void term (void);
void fact (void);
void ct (void);
void mulop (void);

int isrelop (token_t operator);
int ismulop (token_t operator);
int isaddop (token_t operator);
