
package ELearning.services.client.criterioavaliacao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CriterioAvaliacaoService", targetNamespace = "http://services.ELearning/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CriterioAvaliacaoService {


    /**
     * 
     * @param newCriterion
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarCriterio", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.CadastrarCriterio")
    @ResponseWrapper(localName = "cadastrarCriterioResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.CadastrarCriterioResponse")
    @Action(input = "http://services.ELearning/CriterioAvaliacaoService/cadastrarCriterioRequest", output = "http://services.ELearning/CriterioAvaliacaoService/cadastrarCriterioResponse")
    public boolean cadastrarCriterio(
        @WebParam(name = "newCriterion", targetNamespace = "")
        CriterioAvaliacao newCriterion);

    /**
     * 
     * @param criterion
     * @return
     *     returns java.util.List<ELearning.services.client.criterioavaliacao.CriterioAvaliacao>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "procurarCriterio", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.ProcurarCriterio")
    @ResponseWrapper(localName = "procurarCriterioResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.ProcurarCriterioResponse")
    @Action(input = "http://services.ELearning/CriterioAvaliacaoService/procurarCriterioRequest", output = "http://services.ELearning/CriterioAvaliacaoService/procurarCriterioResponse")
    public List<CriterioAvaliacao> procurarCriterio(
        @WebParam(name = "criterion", targetNamespace = "")
        CriterioAvaliacao criterion);

    /**
     * 
     * @param newCriterion
     * @param oldCriterion
     * @return
     *     returns ELearning.services.client.criterioavaliacao.CriterioAvaliacao
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editarCriterio", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.EditarCriterio")
    @ResponseWrapper(localName = "editarCriterioResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.EditarCriterioResponse")
    @Action(input = "http://services.ELearning/CriterioAvaliacaoService/editarCriterioRequest", output = "http://services.ELearning/CriterioAvaliacaoService/editarCriterioResponse")
    public CriterioAvaliacao editarCriterio(
        @WebParam(name = "oldCriterion", targetNamespace = "")
        CriterioAvaliacao oldCriterion,
        @WebParam(name = "newCriterion", targetNamespace = "")
        CriterioAvaliacao newCriterion);

    /**
     * 
     * @param criterion
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletarCriterio", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.DeletarCriterio")
    @ResponseWrapper(localName = "deletarCriterioResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.criterioavaliacao.DeletarCriterioResponse")
    @Action(input = "http://services.ELearning/CriterioAvaliacaoService/deletarCriterioRequest", output = "http://services.ELearning/CriterioAvaliacaoService/deletarCriterioResponse")
    public boolean deletarCriterio(
        @WebParam(name = "criterion", targetNamespace = "")
        CriterioAvaliacao criterion);

}
