
package ELearning.services.client.matricula;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MatriculaService", targetNamespace = "http://services.ELearning/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MatriculaService {


    /**
     * 
     * @param newEnrollment
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarMatricula", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.CadastrarMatricula")
    @ResponseWrapper(localName = "cadastrarMatriculaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.CadastrarMatriculaResponse")
    @Action(input = "http://services.ELearning/MatriculaService/cadastrarMatriculaRequest", output = "http://services.ELearning/MatriculaService/cadastrarMatriculaResponse")
    public boolean cadastrarMatricula(
        @WebParam(name = "newEnrollment", targetNamespace = "")
        Matricula newEnrollment);

    /**
     * 
     * @param enrollment
     * @return
     *     returns java.util.List<ELearning.services.client.matricula.Matricula>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "procurarMatricula", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.ProcurarMatricula")
    @ResponseWrapper(localName = "procurarMatriculaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.ProcurarMatriculaResponse")
    @Action(input = "http://services.ELearning/MatriculaService/procurarMatriculaRequest", output = "http://services.ELearning/MatriculaService/procurarMatriculaResponse")
    public List<Matricula> procurarMatricula(
        @WebParam(name = "enrollment", targetNamespace = "")
        Matricula enrollment);

    /**
     * 
     * @param oldEnrollment
     * @param newEnrollment
     * @return
     *     returns ELearning.services.client.matricula.Matricula
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editarMatricula", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.EditarMatricula")
    @ResponseWrapper(localName = "editarMatriculaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.EditarMatriculaResponse")
    @Action(input = "http://services.ELearning/MatriculaService/editarMatriculaRequest", output = "http://services.ELearning/MatriculaService/editarMatriculaResponse")
    public Matricula editarMatricula(
        @WebParam(name = "oldEnrollment", targetNamespace = "")
        Matricula oldEnrollment,
        @WebParam(name = "newEnrollment", targetNamespace = "")
        Matricula newEnrollment);

    /**
     * 
     * @param enrollment
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletarMatricula", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.DeletarMatricula")
    @ResponseWrapper(localName = "deletarMatriculaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.matricula.DeletarMatriculaResponse")
    @Action(input = "http://services.ELearning/MatriculaService/deletarMatriculaRequest", output = "http://services.ELearning/MatriculaService/deletarMatriculaResponse")
    public boolean deletarMatricula(
        @WebParam(name = "enrollment", targetNamespace = "")
        Matricula enrollment);

}
