/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ELearningDesktopRelatorios.java
 *
 * Created on 04/07/2011, 22:20:24
 */

package elearningdesktopclient;

import ELearning.Access.web.ReportAccess;
import ELearning.services.client.relatorios.Aluno;
import ELearning.services.client.relatorios.DisciplineGradeReport;
import ELearning.services.client.relatorios.EnrollmentCountReport;
import ELearning.services.client.relatorios.EnrollmentCriteriaReport;
import ELearning.services.client.relatorios.Professor;
import ELearning.services.client.relatorios.StudentDisciplineGradeReport;
import ELearning.services.client.relatorios.StudentEnrollmentModel;
import ELearning.services.client.relatorios.StudentListReport;
import java.util.List;

/**
 *
 * @author Acessa SP
 */
public class ELearningDesktopRelatorios extends javax.swing.JDialog {
    Professor professor = null;
    Aluno aluno = null;

    /** Creates new form ELearningDesktopRelatorios */
    public ELearningDesktopRelatorios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** Creates new form ELearningDesktopRelatorios */
    public ELearningDesktopRelatorios(java.awt.Frame parent, boolean modal, Professor professor) {
        super(parent, modal);
        initComponents();
        this.professor = professor;
    }

    /** Creates new form ELearningDesktopRelatorios */
    public ELearningDesktopRelatorios(java.awt.Frame parent, boolean modal, Aluno aluno) {
        super(parent, modal);
        initComponents();
        this.aluno = aluno;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReport1 = new javax.swing.JButton();
        btnReport6 = new javax.swing.JButton();
        btnReport4 = new javax.swing.JButton();
        btnReport5 = new javax.swing.JButton();
        btnReport3 = new javax.swing.JButton();
        btnReport2 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnReport8 = new javax.swing.JButton();
        btnReport7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(elearningdesktopclient.ELearningDesktopClientApp.class).getContext().getResourceMap(ELearningDesktopRelatorios.class);
        btnReport1.setText(resourceMap.getString("btnReport1.text")); // NOI18N
        btnReport1.setName("btnReport1"); // NOI18N
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });

        btnReport6.setText(resourceMap.getString("btnReport6.text")); // NOI18N
        btnReport6.setName("btnReport6"); // NOI18N
        btnReport6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport6ActionPerformed(evt);
            }
        });

        btnReport4.setText(resourceMap.getString("btnReport4.text")); // NOI18N
        btnReport4.setName("btnReport4"); // NOI18N
        btnReport4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport4ActionPerformed(evt);
            }
        });

        btnReport5.setText(resourceMap.getString("btnReport5.text")); // NOI18N
        btnReport5.setName("btnReport5"); // NOI18N
        btnReport5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport5ActionPerformed(evt);
            }
        });

        btnReport3.setText(resourceMap.getString("btnReport3.text")); // NOI18N
        btnReport3.setName("btnReport3"); // NOI18N
        btnReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport3ActionPerformed(evt);
            }
        });

        btnReport2.setText(resourceMap.getString("btnReport2.text")); // NOI18N
        btnReport2.setName("btnReport2"); // NOI18N
        btnReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport2ActionPerformed(evt);
            }
        });

        btnLogout.setText(resourceMap.getString("btnLogout.text")); // NOI18N
        btnLogout.setName("btnLogout"); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnReport8.setText(resourceMap.getString("btnReport8.text")); // NOI18N
        btnReport8.setName("btnReport8"); // NOI18N
        btnReport8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport8ActionPerformed(evt);
            }
        });

        btnReport7.setText(resourceMap.getString("btnReport7.text")); // NOI18N
        btnReport7.setName("btnReport7"); // NOI18N
        btnReport7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReport1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReport3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnReport5, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addComponent(btnReport8, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addComponent(btnReport6, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addComponent(btnReport7, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                    .addComponent(btnReport4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnLogout)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReport1)
                .addGap(18, 18, 18)
                .addComponent(btnReport2)
                .addGap(18, 18, 18)
                .addComponent(btnReport3)
                .addGap(18, 18, 18)
                .addComponent(btnReport4)
                .addGap(18, 18, 18)
                .addComponent(btnReport5)
                .addGap(18, 18, 18)
                .addComponent(btnReport6)
                .addGap(18, 18, 18)
                .addComponent(btnReport7)
                .addGap(18, 18, 18)
                .addComponent(btnReport8)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        // TODO add your handling code here:
        List<Professor> list = ReportAccess.getAllProfessors();
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport1ActionPerformed

    private void btnReport6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport6ActionPerformed
        // TODO add your handling code here:
        List<EnrollmentCountReport> list = ReportAccess.getEnrollmentCount(professor);
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport6ActionPerformed

    private void btnReport4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport4ActionPerformed
        // TODO add your handling code here:
        List<EnrollmentCriteriaReport> list = ReportAccess.getEnrollmentCriteria(professor);
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport4ActionPerformed

    private void btnReport5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport5ActionPerformed
        // TODO add your handling code here:
        List<StudentListReport> list = ReportAccess.getStudentList(professor);
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport5ActionPerformed

    private void btnReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport3ActionPerformed
        // TODO add your handling code here:
        List<StudentEnrollmentModel> list = ReportAccess.getAllDisciplines();
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport3ActionPerformed

    private void btnReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport2ActionPerformed
        // TODO add your handling code here:
        List<Aluno> list = ReportAccess.getAllStudents();
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
}//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReport8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport8ActionPerformed
        // TODO add your handling code here:
        List<StudentDisciplineGradeReport> list = ReportAccess.getStudentDisciplineGrade(aluno);
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport8ActionPerformed

    private void btnReport7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport7ActionPerformed
        // TODO add your handling code here:
        List<DisciplineGradeReport> list = ReportAccess.getDisciplineGrade(professor);
        Report report = new Report(new javax.swing.JFrame(),true,list);
        report.setVisible(true);
}//GEN-LAST:event_btnReport7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ELearningDesktopRelatorios dialog = new ELearningDesktopRelatorios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    public javax.swing.JButton btnReport1;
    public javax.swing.JButton btnReport2;
    public javax.swing.JButton btnReport3;
    public javax.swing.JButton btnReport4;
    public javax.swing.JButton btnReport5;
    public javax.swing.JButton btnReport6;
    public javax.swing.JButton btnReport7;
    public javax.swing.JButton btnReport8;
    // End of variables declaration//GEN-END:variables

}
