
package ELearning.services.client.aluno;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlunoService", targetNamespace = "http://services.ELearning/", wsdlLocation = "http://localhost:9960/ELearningServices/AlunoService?wsdl")
public class AlunoService_Service
    extends Service
{

    private final static URL ALUNOSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALUNOSERVICE_EXCEPTION;
    private final static QName ALUNOSERVICE_QNAME = new QName("http://services.ELearning/", "AlunoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9960/ELearningServices/AlunoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALUNOSERVICE_WSDL_LOCATION = url;
        ALUNOSERVICE_EXCEPTION = e;
    }

    public AlunoService_Service() {
        super(__getWsdlLocation(), ALUNOSERVICE_QNAME);
    }

    public AlunoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALUNOSERVICE_QNAME, features);
    }

    public AlunoService_Service(URL wsdlLocation) {
        super(wsdlLocation, ALUNOSERVICE_QNAME);
    }

    public AlunoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALUNOSERVICE_QNAME, features);
    }

    public AlunoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlunoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlunoService
     */
    @WebEndpoint(name = "AlunoServicePort")
    public AlunoService getAlunoServicePort() {
        return super.getPort(new QName("http://services.ELearning/", "AlunoServicePort"), AlunoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlunoService
     */
    @WebEndpoint(name = "AlunoServicePort")
    public AlunoService getAlunoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ELearning/", "AlunoServicePort"), AlunoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALUNOSERVICE_EXCEPTION!= null) {
            throw ALUNOSERVICE_EXCEPTION;
        }
        return ALUNOSERVICE_WSDL_LOCATION;
    }

}
