/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtarefatorCompEvolutivaBases.java
 *
 * Created on 12/06/2011, 19:06:41
 */

package atarefatorcompevolutiva;

import atarefatorcompevolutiva.model.Pesos;
import atarefatorcompevolutiva.model.Tarefa;
import atarefatorcompevolutiva.util.Bases;
import java.util.List;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author user
 */
public class AtarefatorCompEvolutivaBases extends javax.swing.JDialog {
    List<Tarefa> tarefas;
    Vector<String> vetorTarefas;
    JList listaTarefas;
    JButton buttonEdit, buttonExclude;
    Pesos pesos;
    AtarefatorCompEvolutivaView view;

    /** Creates new form AtarefatorCompEvolutivaBases */
    public AtarefatorCompEvolutivaBases(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    AtarefatorCompEvolutivaBases(java.awt.Frame parent, boolean modal, AtarefatorCompEvolutivaView view) {
        super(parent, modal);
        initComponents();
        this.tarefas = view.getTarefas();
        this.vetorTarefas = view.getVetorTarefas();
        this.listaTarefas = view.getListaTarefas();
        this.pesos = view.getPesos();
        this.buttonEdit = view.getBotaoEditarCancelar();
        this.buttonExclude = view.getBotaoExcluirOK();
        this.view = view;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoFechar = new javax.swing.JButton();
        botaoBase4 = new javax.swing.JButton();
        botaoBase3 = new javax.swing.JButton();
        botaoBase2 = new javax.swing.JButton();
        botaoBase1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(atarefatorcompevolutiva.AtarefatorCompEvolutivaApp.class).getContext().getResourceMap(AtarefatorCompEvolutivaBases.class);
        botaoFechar.setText(resourceMap.getString("botaoFechar.text")); // NOI18N
        botaoFechar.setName("botaoFechar"); // NOI18N
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        botaoBase4.setText(resourceMap.getString("botaoBase4.text")); // NOI18N
        botaoBase4.setToolTipText(resourceMap.getString("botaoBase4.toolTipText")); // NOI18N
        botaoBase4.setName("botaoBase4"); // NOI18N
        botaoBase4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBase4ActionPerformed(evt);
            }
        });

        botaoBase3.setText(resourceMap.getString("botaoBase3.text")); // NOI18N
        botaoBase3.setToolTipText(resourceMap.getString("botaoBase3.toolTipText")); // NOI18N
        botaoBase3.setName("botaoBase3"); // NOI18N
        botaoBase3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBase3ActionPerformed(evt);
            }
        });

        botaoBase2.setText(resourceMap.getString("botaoBase2.text")); // NOI18N
        botaoBase2.setToolTipText(resourceMap.getString("botaoBase2.toolTipText")); // NOI18N
        botaoBase2.setName("botaoBase2"); // NOI18N
        botaoBase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBase2ActionPerformed(evt);
            }
        });

        botaoBase1.setText(resourceMap.getString("botaoBase1.text")); // NOI18N
        botaoBase1.setToolTipText(resourceMap.getString("botaoBase1.toolTipText")); // NOI18N
        botaoBase1.setName("botaoBase1"); // NOI18N
        botaoBase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBase1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoBase4, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(botaoFechar)
                    .addComponent(botaoBase3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(botaoBase2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(botaoBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoBase2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoBase3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoBase4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoBase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBase1ActionPerformed
        // TODO add your handling code here:
        tarefas = Bases.base1();
        view.setTarefas(tarefas);
        vetorTarefas = Bases.vectorBase1();
        view.setVetorTarefas(vetorTarefas);
        listaTarefas.setListData(vetorTarefas);
        listaTarefas.setSelectedIndex(0);
        view.getBotaoExcluirOK().setEnabled(true);
        view.getBotaoEditarCancelar().setEnabled(true);
        dispose();
    }//GEN-LAST:event_botaoBase1ActionPerformed

    private void botaoBase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBase2ActionPerformed
        // TODO add your handling code here:
        tarefas = Bases.base2();
        view.setTarefas(tarefas);
        vetorTarefas = Bases.vectorBase2();
        view.setVetorTarefas(vetorTarefas);
        listaTarefas.setListData(vetorTarefas);
        listaTarefas.setSelectedIndex(0);
        view.getBotaoExcluirOK().setEnabled(true);
        view.getBotaoEditarCancelar().setEnabled(true);
        dispose();
    }//GEN-LAST:event_botaoBase2ActionPerformed

    private void botaoBase3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBase3ActionPerformed
        // TODO add your handling code here:
        tarefas = Bases.base3();
        view.setTarefas(tarefas);
        vetorTarefas = Bases.vectorBase3();
        view.setVetorTarefas(vetorTarefas);
        listaTarefas.setListData(vetorTarefas);
        listaTarefas.setSelectedIndex(0);
        view.getBotaoExcluirOK().setEnabled(true);
        view.getBotaoEditarCancelar().setEnabled(true);
        dispose();
    }//GEN-LAST:event_botaoBase3ActionPerformed

    private void botaoBase4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBase4ActionPerformed
        // TODO add your handling code here:
        tarefas = Bases.base4(pesos);
        view.setTarefas(tarefas);
        vetorTarefas = Bases.vectorBase4();
        view.setVetorTarefas(vetorTarefas);
        listaTarefas.setListData(vetorTarefas);
        listaTarefas.setSelectedIndex(0);
        view.getBotaoExcluirOK().setEnabled(true);
        view.getBotaoEditarCancelar().setEnabled(true);
        dispose();
    }//GEN-LAST:event_botaoBase4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtarefatorCompEvolutivaBases dialog = new AtarefatorCompEvolutivaBases(new javax.swing.JFrame(), true);
                /*dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });*/
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBase1;
    private javax.swing.JButton botaoBase2;
    private javax.swing.JButton botaoBase3;
    private javax.swing.JButton botaoBase4;
    private javax.swing.JButton botaoFechar;
    // End of variables declaration//GEN-END:variables

}
