
package ELearning.services.client.disciplina;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DisciplinaService", targetNamespace = "http://services.ELearning/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DisciplinaService {


    /**
     * 
     * @param newDiscipline
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarDisciplina", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.CadastrarDisciplina")
    @ResponseWrapper(localName = "cadastrarDisciplinaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.CadastrarDisciplinaResponse")
    @Action(input = "http://services.ELearning/DisciplinaService/cadastrarDisciplinaRequest", output = "http://services.ELearning/DisciplinaService/cadastrarDisciplinaResponse")
    public boolean cadastrarDisciplina(
        @WebParam(name = "newDiscipline", targetNamespace = "")
        Disciplina newDiscipline);

    /**
     * 
     * @param discipline
     * @return
     *     returns java.util.List<ELearning.services.client.disciplina.Disciplina>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "procurarDisciplina", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.ProcurarDisciplina")
    @ResponseWrapper(localName = "procurarDisciplinaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.ProcurarDisciplinaResponse")
    @Action(input = "http://services.ELearning/DisciplinaService/procurarDisciplinaRequest", output = "http://services.ELearning/DisciplinaService/procurarDisciplinaResponse")
    public List<Disciplina> procurarDisciplina(
        @WebParam(name = "discipline", targetNamespace = "")
        Disciplina discipline);

    /**
     * 
     * @param newDiscipline
     * @param oldDiscipline
     * @return
     *     returns ELearning.services.client.disciplina.Disciplina
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editarDisciplina", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.EditarDisciplina")
    @ResponseWrapper(localName = "editarDisciplinaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.EditarDisciplinaResponse")
    @Action(input = "http://services.ELearning/DisciplinaService/editarDisciplinaRequest", output = "http://services.ELearning/DisciplinaService/editarDisciplinaResponse")
    public Disciplina editarDisciplina(
        @WebParam(name = "oldDiscipline", targetNamespace = "")
        Disciplina oldDiscipline,
        @WebParam(name = "newDiscipline", targetNamespace = "")
        Disciplina newDiscipline);

    /**
     * 
     * @param discipline
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletarDisciplina", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.DeletarDisciplina")
    @ResponseWrapper(localName = "deletarDisciplinaResponse", targetNamespace = "http://services.ELearning/", className = "ELearning.services.client.disciplina.DeletarDisciplinaResponse")
    @Action(input = "http://services.ELearning/DisciplinaService/deletarDisciplinaRequest", output = "http://services.ELearning/DisciplinaService/deletarDisciplinaResponse")
    public boolean deletarDisciplina(
        @WebParam(name = "discipline", targetNamespace = "")
        Disciplina discipline);

}
