
package ELearning.services.client.pessoa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PessoaService", targetNamespace = "http://services.ELearning/", wsdlLocation = "http://localhost:9960/ELearningServices/PessoaService?wsdl")
public class PessoaService_Service
    extends Service
{

    private final static URL PESSOASERVICE_WSDL_LOCATION;
    private final static WebServiceException PESSOASERVICE_EXCEPTION;
    private final static QName PESSOASERVICE_QNAME = new QName("http://services.ELearning/", "PessoaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9960/ELearningServices/PessoaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PESSOASERVICE_WSDL_LOCATION = url;
        PESSOASERVICE_EXCEPTION = e;
    }

    public PessoaService_Service() {
        super(__getWsdlLocation(), PESSOASERVICE_QNAME);
    }

    public PessoaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PESSOASERVICE_QNAME, features);
    }

    public PessoaService_Service(URL wsdlLocation) {
        super(wsdlLocation, PESSOASERVICE_QNAME);
    }

    public PessoaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PESSOASERVICE_QNAME, features);
    }

    public PessoaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PessoaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PessoaService
     */
    @WebEndpoint(name = "PessoaServicePort")
    public PessoaService getPessoaServicePort() {
        return super.getPort(new QName("http://services.ELearning/", "PessoaServicePort"), PessoaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PessoaService
     */
    @WebEndpoint(name = "PessoaServicePort")
    public PessoaService getPessoaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ELearning/", "PessoaServicePort"), PessoaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PESSOASERVICE_EXCEPTION!= null) {
            throw PESSOASERVICE_EXCEPTION;
        }
        return PESSOASERVICE_WSDL_LOCATION;
    }

}
