program ENTRADA;

var a,b,c,d,x,y : integer;
	w: boolean;

procedure P1();
begin
	write("Digite valor de b: ");
	read (b);
	
	d:=0;
end;

function F1(): integer;
begin
	d:= (2*a) * b;
	for x:= 1 to 3
	do
	  
		y:= y + 1;
end;

begin
	a:=0;
	b:=2;
	if (b=2)or (a= 0)
		then
			begin
				a:= b * c;
				a:= a div 3;
				c:= 2 / b
			end
		else
			begin
				repeat
				c:= a + 1;
				until ( c >= 2)
			end;
P1();

while ( w =0)
do
	begin
		a:= a / 2;
		b:= b * 2;
	if ( a < 2) and (b>100)
	then
	w:=1
	end;


case a of 	2: a:=3; 
	   	3: a:=5
		
end;		

write("compilador");

F1()

end.


